---
- name: collect netconf_json test cases with xml encoding
  find:
    paths: "{{ role_path }}/tests/netconf_json"
    patterns: "{{ testcase }}.yaml"
  register: test_cases

- name: set test_items
  set_fact: test_items="{{ test_cases.files | map(attribute='path') | list }}"

- name: run test case
  include: "{{ item }}"
  with_items: "{{ test_items }}"


